 <div className="p-8">
          <h2 className="text-2xl font-bold text-[#1454AE] mb-8 flex items-center gap-3">
            Form KreLoan
          </h2>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-10">
              {/* Panel 1: Auto-Generation Setting & Identitas Pengajuan */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {" "}
                <div className="border-2 border-solid  p-6 rounded-lg mb-6 bg-white">
                  <h3 className="text-[#1454AE] text-lg font-semibold mb-6">
                    Identitas Pengajuan
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* No Loan dengan Auto-Generation */}
                    <div className="md:col-span-2">
                      <div className="space-y-2">
                        <div className="flex items-center space-x-2">
                          <Checkbox
                            id="manual-no-loan"
                            checked={isManualNoLoan}
                            onCheckedChange={(checked) => {
                              setIsManualNoLoan(checked as boolean);
                              if (!checked) {
                                const autoGeneratedNoLoan = generateNoLoan();
                                form.setValue("noLoan", autoGeneratedNoLoan);
                              }
                            }}
                          />
                          <label
                            htmlFor="manual-no-loan"
                            className="text-sm font-medium text-gray-700"
                          >
                            Isi No Loan Manual
                          </label>
                        </div>

                        <FormField
                          control={form.control}
                          name="noLoan"
                          render={({ field }) => (
                            <FormItem>
                              <FormLabel className="text-[#525252] font-bold">
                                No Loan{" "}
                                <span className="text-[#D92D20]">*</span>
                              </FormLabel>
                              <FormControl>
                                <Input
                                  className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                                  placeholder={
                                    isManualNoLoan
                                      ? "Masukkan No Loan"
                                      : "Auto Generated"
                                  }
                                  type="text"
                                  {...field}
                                  disabled={!isManualNoLoan}
                                />
                              </FormControl>
                              <FormMessage />
                              {!isManualNoLoan && (
                                <p className="text-xs text-muted-foreground">
                                  Format: kode_cabang + akun_cabang +
                                  jenis_kredit + nasabah_id + sandi_lembaga +
                                  &quot;|M3&quot;
                                </p>
                              )}
                            </FormItem>
                          )}
                        />
                      </div>
                    </div>

                    <FormField
                      control={form.control}
                      name="noPengajuan"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-[#525252] font-bold">
                            No Pengajuan{" "}
                            <span className="text-[#D92D20]">*</span>
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="No Pengajuan"
                              type="text"
                              {...field}
                              disabled={true}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="noPersetujuan"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-[#525252] font-bold">
                            No Persetujuan{" "}
                            <span className="text-[#D92D20]">*</span>
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="No Persetujuan"
                              type="text"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="tglPersetujuan"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-[#525252] font-bold">
                            Tanggal Persetujuan{" "}
                            <span className="text-[#D92D20]">*</span>
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="Tanggal Persetujuan"
                              type="date"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="noFasilitas"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-[#525252] font-bold">
                            No Fasilitas{" "}
                            <span className="text-[#D92D20]">*</span>
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="No Fasilitas"
                              type="text"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="noAlternatif"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-[#525252] font-bold">
                            No Alternatif{" "}
                            <span className="text-[#D92D20]">*</span>
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="No Alternatif"
                              type="text"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>
                </div>
                {/* Panel 2: Data PK & Notaris */}
                <div className="border-2 border-solid  p-6 rounded-lg mb-6 bg-white">
                  <h3 className="text-[#1454AE] text-lg font-semibold mb-6">
                    Data PK & Notaris
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <FormField
                      control={form.control}
                      name="noPkLama"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-medium text-gray-700">
                            No PK Lama
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="No PK Lama"
                              type="text"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="tglPkLama"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-medium text-gray-700">
                            Tanggal PK Lama
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="Tanggal PK Lama"
                              type="date"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="noPkBaru"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-medium text-gray-700">
                            No PK Baru
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="No PK Baru"
                              type="text"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="tglPkBaru"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-medium text-gray-700">
                            Tanggal PK Baru
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="Tanggal PK Baru"
                              type="date"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="noNotaris"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-medium text-gray-700">
                            No Notaris
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="No Notaris"
                              type="text"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="tglNotaris"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-medium text-gray-700">
                            Tanggal Notaris
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="Tanggal Notaris"
                              type="date"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>
                </div>
              </div>

              {/* Panel 3: Informasi Penyaluran */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="border-2 border-solid  p-6 rounded-lg mb-6 bg-white">
                  <h3 className="text-[#1454AE] text-lg font-semibold mb-6">
                    Informasi Penyaluran
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <FormField
                      control={form.control}
                      name="idAo"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-medium text-gray-700">
                            ID AO
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="ID AO"
                              type="text"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="idKelompok"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-medium text-gray-700">
                            ID Kelompok
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="ID Kelompok"
                              type="text"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="idSumberDana"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-medium text-gray-700">
                            ID Sumber Dana
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="ID Sumber Dana"
                              type="text"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="lembagaTakeOver"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-medium text-gray-700">
                            Lembaga Take Over
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="Lembaga Take Over"
                              type="text"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="jenisKredit"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-medium text-gray-700">
                            Jenis Kredit
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="Jenis Kredit"
                              type="text"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>
                </div>

                {/* Panel 4: Kolektibilitas & Distribusi */}
                <div className="border-2 border-solid p-6 rounded-lg mb-6 bg-white">
                  <h3 className="text-[#1454AE] text-lg font-semibold mb-6">
                    Kolektibilitas & Distribusi
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="space-y-2">
                      <label className="text-sm font-medium text-gray-700">
                        Kolektibilitas Jenis
                      </label>
                      <Combobox
                        options={refKolektibilitasJenis}
                        value={form.watch("kolektibilitasJenis") ?? ""}
                        onChange={(val) =>
                          form.setValue("kolektibilitasJenis", val)
                        }
                        title="Kolektibilitas Jenis"
                      />
                    </div>

                    <div className="space-y-2">
                      <label className="text-sm font-medium text-gray-700">
                        Distribusi Hasil
                      </label>
                      <Combobox
                        options={refDistribusiBasil}
                        value={form.watch("distribusiBasil") ?? ""}
                        onChange={(val) =>
                          form.setValue("distribusiBasil", val)
                        }
                        title="Distribusi Hasil"
                      />
                    </div>

                    <FormField
                      control={form.control}
                      name="bankAccount"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-medium text-gray-700">
                            Bank Account
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="Bank Account"
                              type="text"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="jmlDebitur"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-medium text-gray-700">
                            Jumlah Debitur
                          </FormLabel>
                          <FormControl>
                            <Input
                              className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                              placeholder="Jumlah Debitur"
                              type="number"
                              {...field}
                              onChange={(e) => {
                                const value =
                                  e.target.value === ""
                                    ? undefined
                                    : Number(e.target.value);
                                field.onChange(value);
                              }}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>
                </div>
              </div>

              {/* Panel 5: Operasional & Lainnya */}
              <div className="border-2 border-solid  p-6 rounded-lg mb-6 bg-white">
                <h3 className="text-[#1454AE] text-lg font-semibold mb-6">
                  Operasional & Lainnya
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <FormField
                    control={form.control}
                    name="operationSlik"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-sm font-medium text-gray-700">
                          Operation SLIK
                        </FormLabel>
                        <FormControl>
                          <Input
                            className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                            placeholder="Operation SLIK"
                            type="text"
                            {...field}
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="operationSlikPenjamin"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-sm font-medium text-gray-700">
                          Operation SLIK Penjamin
                        </FormLabel>
                        <FormControl>
                          <Input
                            className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                            placeholder="Operation SLIK Penjamin"
                            type="text"
                            {...field}
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="operationSlikResending"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-sm font-medium text-gray-700">
                          Operation SLIK Resending
                        </FormLabel>
                        <FormControl>
                          <Input
                            className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                            placeholder="Operation SLIK Resending"
                            type="text"
                            {...field}
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="cab"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-sm font-medium text-gray-700">
                          Cabang
                        </FormLabel>
                        <FormControl>
                          <Input
                            className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                            placeholder="Cabang"
                            type="text"
                            {...field}
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="userId"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-sm font-medium text-gray-700">
                          User ID
                        </FormLabel>
                        <FormControl>
                          <Input
                            className="h-11 border-gray-300 focus:border-gray-500 focus:ring-gray-500/20 bg-white/70 backdrop-blur-sm"
                            placeholder="User ID"
                            type="text"
                            {...field}
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              </div>

              <div className="flex justify-end space-x-4 pt-4 border-t border-gray-200">
                <Button
                  type="button"
                  variant="outline"
                  onClick={handleBack}
                  className="h-11 px-8 border-gray-300 text-gray-600 hover:bg-gray-50 hover:text-gray-700 transition-colors duration-200"
                >
                  Kembali
                </Button>
                <Button
                  type="submit"
                  className="h-11 px-8 bg-[#1454AE] hover:bg-[#174a96] text-white font-medium shadow-sm hover:shadow-md transition-all duration-200"
                >
                  Simpan
                </Button>
              </div>
            </form>
          </Form>
        </div>
